# Generated by Django 4.0.6 on 2022-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ielts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ielts', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
