# Generated by Django 4.0.6 on 2022-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_english_ielts_delete_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='english',
            old_name='English',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ielts',
            old_name='Ielts',
            new_name='title',
        ),
        migrations.AddField(
            model_name='english',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ielts',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
